version: "3.9"

services :
  
  metric:
    image: 192.168.10.18:5000/metrics
    ports: 
      - "8050:8050"
    networks: 
      - backend
      - frontend
    deploy: 
       placement:
         constraints: [node.labels.metric == true]
  redis:
    image: 192.168.10.18:5000/redis:6.2
    ports:
      - "6379:6379"
    networks:
      - backend
    deploy: 
       placement:
         constraints: [node.labels.redis == true]
  logparser:
    image: 192.168.10.18:5000/logparser
    ports:
      - "5001:5001"
    networks: 
      - frontend
    deploy: 
       placement:
         constraints: [node.labels.logparser == true]
    
  loadbalancer:
    image: 192.168.10.18:5000/nginx
    ports:
      - "80:80"
    networks: 
      - frontend
    deploy: 
       placement:
         constraints: [node.labels.loadbalancer == true]
networks: 
  frontend:
  backend:

